version: "3.9"

services:
  db:
    image: postgres:16
    container_name: myfirstblog-postgres
    environment:
      POSTGRES_DB: myfirstblog
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5438:5432"   # внешний порт:внутренний
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .
    container_name: myfirstblog-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"     # Django доступен на http://localhost:8000
    depends_on:
      - db
    env_file:
      - db.env
volumes:
  postgres_data: